workingforum_forum:
    path:     /
    defaults: { _controller: YosimitsoWorkingForumBundle:Forum:index }
workingforum_subforum:
    path: /view/{subforum_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Forum:subforum }

workingforum_thread:
    path: /view/{subforum_slug}/{thread_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Thread:index }

workingforum_new_thread:
    path: /newthread/{subforum_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Thread:new }
workingforum_lock_thread:
    path: /locked/{subforum_slug}/{thread_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Thread:lock }
workingforum_resolve_thread:
    path: /resolved/{subforum_slug}/{thread_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Thread:resolve }   
workingforum_report_post:
    path: /report/{post_id}
    defaults: { _controller: YosimitsoWorkingForumBundle:Thread:report }

        
workingforum_admin:
    path: /admin
    defaults: { _controller: YosimitsoWorkingForumBundle:Admin:index }
    
workingforum_admin_forum_edit:
    path: /admin/edit/{id}
    defaults: {_controller: YosimitsoWorkingForumBundle:Admin:edit }
    
workingforum_admin_forum_add:
    path: /admin/add
    defaults: {_controller: YosimitsoWorkingForumBundle:Admin:add }

workingforum_admin_install_settings:
    path: /admin/install-settings
    defaults: {_controller: YosimitsoWorkingForumBundle:Admin:installSettings }
workingforum_admin_report:
    path: /admin/report
    defaults: {_controller: YosimitsoWorkingForumBundle:Admin:report }
workingforum_admin_user:
    path: /admin/user
    defaults: {_controller: YosimitsoWorkingForumBundle:Admin:userList }    
workingforum_admin_report_action_moderate:
    path: /admin/reportaction/moderate
    defaults: {_controller: YosimitsoWorkingForumBundle:Admin:reportActionModerate }
    
workingforum_admin_report_action_good:
    path: /admin/reportaction/good
    defaults: {_controller: YosimitsoWorkingForumBundle:Admin:reportActionGood }
workingforum_search:
    path: /search
    defaults: {_controller: YosimitsoWorkingForumBundle:Search:index }
