workingforum_forum:
    path:     /
    defaults: { _controller: yosimitso_workingforum.controller.forum:indexAction }

workingforum_subforum:
    path: /{forum_slug}/{subforum_slug}
    defaults: { _controller: yosimitso_workingforum.controller.forum:subforumAction }

workingforum_thread:
    path: /{forum_slug}/{subforum_slug}/{thread_slug}
    defaults: { _controller: yosimitso_workingforum.controller.thread:indexAction }

workingforum_new_thread:
    path: /{forum_slug}/{subforum_slug}/new
    defaults: { _controller: yosimitso_workingforum.controller.thread:newAction }

workingforum_lock_thread:
    path: /{forum_slug}/{subforum_slug}/{thread_slug}/lock
    defaults: { _controller: yosimitso_workingforum.controller.thread:lockAction }

workingforum_pin_thread:
    path: /{forum_slug}/{subforum_slug}/{thread_slug}/pin
    defaults: { _controller: yosimitso_workingforum.controller.thread:pinAction }

workingforum_resolve_thread:
    path: /{forum_slug}/{subforum_slug}/{thread_slug}/resolved
    defaults: { _controller: yosimitso_workingforum.controller.thread:resolveAction }

workingforum_report_post:
    path: /report/{post_id}
    defaults: { _controller: yosimitso_workingforum.controller.thread:reportAction }

workingforum_move_thread:
    path: /movethread
    defaults: { _controller: yosimitso_workingforum.controller.thread:moveThreadAction }

workingforum_delete_thread:
    path: /deletethread/{threadSlug}
    defaults: { _controller: yosimitso_workingforum.controller.thread:deleteThreadAction }

workingforum_admin:
    path: /admin
    defaults: { _controller: yosimitso_workingforum.controller.admin:indexAction }

workingforum_admin_forum_edit:
    path: /admin/forum/edit/{id}
    defaults: {_controller: yosimitso_workingforum.controller.admin_forum:editAction }

workingforum_admin_forum_add:
    path: /admin/forum/add
    defaults: {_controller: yosimitso_workingforum.controller.admin_forum:addAction }

workingforum_admin_delete_forum:
    path: /admin/forum/delete/{forum_id}
    defaults: {_controller: yosimitso_workingforum.controller.admin_forum:deleteForumAction }

workingforum_admin_forum_rules:
    path: /admin/rules
    defaults: {_controller: yosimitso_workingforum.controller.admin_rules:rulesAction }

workingforum_admin_edit_forum_rules:
    path: /admin/rules/edit/{lang}
    defaults: {_controller: yosimitso_workingforum.controller.admin_rules:rulesEditAction }

workingforum_admin_new_forum_rules:
    path: /admin/rules/new/{lang}
    defaults:
          _controller: yosimitso_workingforum.controller.admin_rules:rulesNewAction
          newLang: true

workingforum_admin_install_settings:
    path: /admin/install-settings
    defaults: {_controller: yosimitso_workingforum.controller.admin:installSettingsAction }

workingforum_admin_report:
    path: /admin/report
    defaults: {_controller: yosimitso_workingforum.controller.admin_report:reportAction }
workingforum_admin_report_history:
    path: /admin/report/history
    defaults: {_controller: yosimitso_workingforum.controller.admin_report:reportHistoryAction }

workingforum_admin_report_action_moderate:
    path: /admin/reportaction/moderate
    defaults: {_controller: yosimitso_workingforum.controller.admin_report:reportActionModerateAction }

workingforum_admin_report_action_good:
    path: /admin/reportaction/good
    defaults: {_controller: yosimitso_workingforum.controller.admin_report:reportActionGoodAction }

workingforum_admin_user:
    path: /admin/users
    defaults: {_controller: yosimitso_workingforum.controller.admin_users:userListAction }

workingforum_search:
    path: /search
    defaults: {_controller: yosimitso_workingforum.controller.search:indexAction }

workingforum_vote_up:
    path: /voteup
    defaults: { _controller: yosimitso_workingforum.controller.post:voteUpAction }

workingforum_rules:
    path: rules
    defaults: { _controller: yosimitso_workingforum.controller.forum:rulesAction}

workingforum_rules_locale:
    path: rules/{locale}
    defaults: { _controller: yosimitso_workingforum.controller.forum:rulesAction}

workingforum_add_subscription:
    path: addsubscription/{threadId}
    defaults: { _controller: yosimitso_workingforum.controller.thread:addSubscriptionAction}

workingforum_cancel_subscription:
    path: cancelsubscription/{threadId}
    defaults: { _controller: yosimitso_workingforum.controller.thread:cancelSubscriptionAction}