workingforum_forum:
    path:     /
    defaults: { _controller: YosimitsoWorkingForumBundle:Forum:index }
workingforum_subforum:
    path: /view/{subforum_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Forum:subforum }

workingforum_thread:
    path: /view/{subforum_slug}/{thread_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Thread:index }

workingforum_new_thread:
    path: /newthread/{subforum_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Thread:new }
workingforum_lock_thread:
    path: /locked/{subforum_slug}/{thread_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Thread:lock }
workingforum_resolve_thread:
    path: /resolved/{subforum_slug}/{thread_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Thread:resolve }
workingforum_admin:
    path: /admin
    defaults: { _controller: YosimitsoWorkingForumBundle:Admin:index }
    
workingforum_admin_forum_edit:
    path: /admin/edit/{id}
    defaults: {_controller: YosimitsoWorkingForumBundle:Admin:edit }

workingforum_admin_install_settings:
    path: /admin/install-settings
    defaults: {_controller: YosimitsoWorkingForumBundle:Admin:installSettings }
