workingforum_forum:
    path:     /
    defaults: { _controller: YosimitsoWorkingForumBundle:Forum:index }
workingforum_subforum:
    path: /view/{subforum_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Forum:subforum }

workingforum_topic:
    path: /view/{subforum_slug}/{topic_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Topic:index }

workingforum_new_topic:
    path: /newtopic/{subforum_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Topic:new }
workingforum_lock_topic:
    path: /locked/{subforum_slug}/{topic_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Topic:lock }
workingforum_resolve_topic:
    path: /resolved/{subforum_slug}/{topic_slug}
    defaults: { _controller: YosimitsoWorkingForumBundle:Topic:resolve }
workingforum_admin:
    path: /admin
    defaults: { _controller: YosimitsoWorkingForumBundle:Admin:index }
    
workingforum_admin_forum_edit:
    path: /admin/edit/{id}
    defaults: {_controller: YosimitsoWorkingForumBundle:Admin:edit }

