parameters:


services:
    yosimitso_workingforum_base_controller:
        class: Yosimitso\WorkingForumBundle\Controller\BaseController
        calls:
          - ["setParameters",["@doctrine.orm.entity_manager","@yosimitso_workingforum_authorization","@=service('security.token_storage').getToken().getUser()","@session", "@translator", "@knp_paginator", "@templating"]]

    yosimitso_workingforum_forum_controller:
        class: Yosimitso\WorkingForumBundle\Controller\ForumController
        parent: yosimitso_workingforum_base_controller
        public: true

    yosimitso_workingforum_thread_controller:
        class: Yosimitso\WorkingForumBundle\Controller\ThreadController
        parent: yosimitso_workingforum_base_controller
        public: true
        arguments:
          - "@yosimitso_workingforum_util_fileuploader"
          - "@yosimitso_workingforum_smiley"
          - "@yosimitso_workingforum_service_thread"

    yosimitso_workingforum_admin_controller:
        class: Yosimitso\WorkingForumBundle\Controller\Admin\AdminController
        parent: yosimitso_workingforum_base_controller
        public: true

    yosimitso_workingforum_admin_forum_controller:
        class: Yosimitso\WorkingForumBundle\Controller\Admin\AdminForumController
        parent: yosimitso_workingforum_base_controller
        public: true

    yosimitso_workingforum_admin_report_controller:
        class: Yosimitso\WorkingForumBundle\Controller\Admin\AdminReportController
        parent: yosimitso_workingforum_base_controller
        public: true

    yosimitso_workingforum_admin_rules_controller:
        class: Yosimitso\WorkingForumBundle\Controller\Admin\AdminRulesController
        parent: yosimitso_workingforum_base_controller
        public: true
        arguments:
        - "@yosimitso_workingforum_smiley"

    yosimitso_workingforum_admin_users_controller:
        class: Yosimitso\WorkingForumBundle\Controller\Admin\AdminUsersController
        parent: yosimitso_workingforum_base_controller
        public: true

    yosimitso_workingforum_search_controller:
        class: Yosimitso\WorkingForumBundle\Controller\SearchController
        parent: yosimitso_workingforum_base_controller
        public: true

    yosimitso_workingforum_post_controller:
        class: Yosimitso\WorkingForumBundle\Controller\PostController
        parent: yosimitso_workingforum_base_controller
        public: true
        arguments:
          - "@yosimitso_workingforum_service_thread"

    yosimitso_workingforum_smiley:
        class: Yosimitso\WorkingForumBundle\Twig\Extension\SmileyTwigExtension
        tags:
            -  { name: twig.extension }
        arguments: ["@request_stack", "@assets.packages"]

    yosimitso_workingforum_quote:
        class: Yosimitso\WorkingForumBundle\Twig\Extension\QuoteTwigExtension
        tags:
            -  { name: twig.extension }
        arguments: ["@doctrine.orm.entity_manager", "@translator"]
    yosimitso_workingforum_config:
        class: Yosimitso\WorkingForumBundle\Twig\Extension\ConfigurationTwigExtension
        tags:
            - { name: twig.extension }
        arguments: ["%yosimitso_working_forum.theme_color%"]

    yosimitso_workingforum_authorization:
        class: Yosimitso\WorkingForumBundle\Security\Authorization
        arguments :
            - "@security.authorization_checker"
            - "@security.token_storage"
            - "%yosimitso_working_forum.allow_anonymous_read%"

    yosimitso_workingforum_util_fileuploader:
        class: Yosimitso\WorkingForumBundle\Util\FileUploader
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%yosimitso_working_forum.file_upload%"
            - "@translator"

    yosimitso_workingforum_util_subscription:
        class: Yosimitso\WorkingForumBundle\Util\Subscription
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mailer"
            - "@translator"
            - "%yosimitso_working_forum.site_title%"
            - "%swiftmailer.sender_address%"
            - "@templating"


    yosimitso_workingforum_listener.post:
        class: Yosimitso\WorkingForumBundle\Event\PostEvent
        arguments:
            - "%yosimitso_working_forum.post_flood_sec%"
            - "@translator"
            - "@yosimitso_workingforum_util_subscription"
            - "%yosimitso_working_forum.thread_subscription%"
        tags:
          - { name: doctrine.event_listener, event: prePersist}
          - { name: doctrine.event_listener, event: postPersist}


    yosimitso_workingforum_service_thread:
        class: Yosimitso\WorkingForumBundle\Service\ThreadService
        arguments:
            - "%yosimitso_working_forum.lock_thread_older_than%"
            - "@knp_paginator"
            - "%yosimitso_working_forum.post_per_page%"
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
            - "@@yosimitso_workingforum_authorization"

