parameters:


services:
    yosimitso_workingforum_smiley:
        class: Yosimitso\WorkingForumBundle\Twig\Extension\SmileyTwigExtension
        tags:
            -  { name: twig.extension }
        arguments: 
            request: "@request_stack"
            asset: "@twig.extension.assets"
        
    yosimitso_workingforum_quote:
        class: Yosimitso\WorkingForumBundle\Twig\Extension\QuoteTwigExtension
        tags:
            -  { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"
            trans: "@translator"

