parameters:


services:
  yosimitso_workingforum.controller.base:
    class: Yosimitso\WorkingForumBundle\Controller\BaseController
    calls:
      - ["setParameters",["@doctrine.orm.entity_manager","@yosimitso_workingforum.security.authorization","@=service('security.token_storage').getToken().getUser()","@session", "@translator", "@knp_paginator", "@templating"]]

  yosimitso_workingforum.controller.forum:
    class: Yosimitso\WorkingForumBundle\Controller\ForumController
    parent: yosimitso_workingforum.controller.base
    public: true

  yosimitso_workingforum.controller.thread:
    class: Yosimitso\WorkingForumBundle\Controller\ThreadController
    parent: yosimitso_workingforum.controller.base
    public: true
    arguments:
      - "@yosimitso_workingforum.service.fileuploader"
      - "@yosimitso_workingforum.extension.smiley"
      - "@yosimitso_workingforum.service.thread"

  yosimitso_workingforum.controller.admin:
    class: Yosimitso\WorkingForumBundle\Controller\Admin\AdminController
    parent: yosimitso_workingforum.controller.base
    public: true

  yosimitso_workingforum.controller.admin_forum:
    class: Yosimitso\WorkingForumBundle\Controller\Admin\AdminForumController
    parent: yosimitso_workingforum.controller.base
    public: true

  yosimitso_workingforum.controller.admin_report:
    class: Yosimitso\WorkingForumBundle\Controller\Admin\AdminReportController
    parent: yosimitso_workingforum.controller.base
    public: true

  yosimitso_workingforum.controller.admin_rules:
    class: Yosimitso\WorkingForumBundle\Controller\Admin\AdminRulesController
    parent: yosimitso_workingforum.controller.base
    public: true
    arguments:
      - "@yosimitso_workingforum.extension.smiley"

  yosimitso_workingforum.controller.admin_users:
    class: Yosimitso\WorkingForumBundle\Controller\Admin\AdminUsersController
    parent: yosimitso_workingforum.controller.base
    public: true

  yosimitso_workingforum.controller.search:
    class: Yosimitso\WorkingForumBundle\Controller\SearchController
    parent: yosimitso_workingforum.controller.base
    public: true

  yosimitso_workingforum.controller.post:
    class: Yosimitso\WorkingForumBundle\Controller\PostController
    parent: yosimitso_workingforum.controller.base
    public: true
    arguments:
      - "@yosimitso_workingforum.service.thread"

  yosimitso_workingforum.extension.smiley:
    class: Yosimitso\WorkingForumBundle\Twig\Extension\SmileyTwigExtension
    tags:
      - { name: twig.extension }
    arguments: ["@request_stack", "@assets.packages"]

  yosimitso_workingforum.extension.quote:
    class: Yosimitso\WorkingForumBundle\Twig\Extension\QuoteTwigExtension
    tags:
      - { name: twig.extension }
    arguments: ["@doctrine.orm.entity_manager", "@translator"]

  yosimitso_workingforum.extension.config:
    class: Yosimitso\WorkingForumBundle\Twig\Extension\ConfigurationTwigExtension
    tags:
      - { name: twig.extension }
    arguments: ["%yosimitso_working_forum.theme_color%"]

  yosimitso_workingforum.security.authorization:
    class: Yosimitso\WorkingForumBundle\Security\Authorization
    arguments:
      - "@security.authorization_checker"
      - "@security.token_storage"
      - "%yosimitso_working_forum.allow_anonymous_read%"

  yosimitso_workingforum.service.fileuploader:
    class: Yosimitso\WorkingForumBundle\Service\FileUploaderService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "%yosimitso_working_forum.file_upload%"
      - "@translator"

  yosimitso_workingforum.service.subscription:
    class: Yosimitso\WorkingForumBundle\Service\SubscriptionService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@mailer"
      - "@translator"
      - "%yosimitso_working_forum.site_title%"
      - "%swiftmailer.sender_address%"
      - "@templating"


  yosimitso_workingforum.listener.post:
    class: Yosimitso\WorkingForumBundle\Event\PostEvent
    arguments:
      - "%yosimitso_working_forum.post_flood_sec%"
      - "@translator"
      - "@yosimitso_workingforum.service.subscription"
      - "%yosimitso_working_forum.thread_subscription%"
    tags:
      - { name: doctrine.event_listener, event: prePersist}
      - { name: doctrine.event_listener, event: postPersist}


  yosimitso_workingforum.service.thread:
    class: Yosimitso\WorkingForumBundle\Service\ThreadService
    arguments:
      - "%yosimitso_working_forum.lock_thread_older_than%"
      - "@knp_paginator"
      - "%yosimitso_working_forum.post_per_page%"
      - "@request_stack"
      - "@doctrine.orm.entity_manager"
      - "@security.token_storage"
      - "@yosimitso_workingforum.service.fileuploader"
      - "@yosimitso_workingforum.security.authorization"
      - "@yosimitso_workingforum.service.bundle_parameters"
      - "@form.factory"

  yosimitso_workingforum.service.bundle_parameters:
    class: Yosimitso\WorkingForumBundle\Service\BundleParametersService
    arguments:
      - "@service_container"
#      - ["thread_per_page", "%yosimitso_working_forum.thread_per_page%"]
#      - ["post_per_page", "%yosimitso_working_forum.post_per_page%"]
#      - ["date_format", "%yosimitso_working_forum.date_format%"]
#      - ["allow_anonymous_read", "%yosimitso_working_forum.allow_anonymous_read%"]
#      - ["allow_moderator_delete_thread", "%yosimitso_working_forum.allow_moderator_delete_thread%"]
#      - ["theme_color", "%yosimitso_working_forum.theme_color%"]
#      - ["lock_thread_older_than", "%yosimitso_working_forum.lock_thread_older_than%"]
#      - ["vote", "%yosimitso_working_forum.vote%"]
#      - ["file_upload", "%yosimitso_working_forum.file_upload%"]
#      - ["post_flood_sec", "%yosimitso_working_forum.post_flood_sec%"]
#      - ["site_title", "%yosimitso_working_forum.site_title%"]
#      - ["thread_subscription", "%yosimitso_working_forum.thread_subscription%"]
