parameters:


services:
    yosimitso_workingforum_smiley:
        class: Yosimitso\WorkingForumBundle\Twig\Extension\SmileyTwigExtension
        tags:
            -  { name: twig.extension }
        arguments: ['@request_stack']

